//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class emoticons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal emoticons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.emoticons", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to angry.
        /// </summary>
        internal static string angry {
            get {
                return ResourceManager.GetString("angry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to approve.
        /// </summary>
        internal static string approve {
            get {
                return ResourceManager.GetString("approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big eyes.
        /// </summary>
        internal static string bigeyes {
            get {
                return ResourceManager.GetString("bigeyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to big smile.
        /// </summary>
        internal static string bigsmile {
            get {
                return ResourceManager.GetString("bigsmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black eye.
        /// </summary>
        internal static string blackeye {
            get {
                return ResourceManager.GetString("blackeye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blush.
        /// </summary>
        internal static string blush {
            get {
                return ResourceManager.GetString("blush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boggled.
        /// </summary>
        internal static string boggled {
            get {
                return ResourceManager.GetString("boggled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clown.
        /// </summary>
        internal static string clown {
            get {
                return ResourceManager.GetString("clown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cool.
        /// </summary>
        internal static string cool {
            get {
                return ResourceManager.GetString("cool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cyclops.
        /// </summary>
        internal static string cyclops {
            get {
                return ResourceManager.GetString("cyclops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalek.
        /// </summary>
        internal static string dalek {
            get {
                return ResourceManager.GetString("dalek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dead.
        /// </summary>
        internal static string dead {
            get {
                return ResourceManager.GetString("dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ill.
        /// </summary>
        internal static string deadgreen {
            get {
                return ResourceManager.GetString("deadgreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disapprove.
        /// </summary>
        internal static string disapprove {
            get {
                return ResourceManager.GetString("disapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dissapprove.
        /// </summary>
        internal static string dissapprove {
            get {
                return ResourceManager.GetString("dissapprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eightball.
        /// </summary>
        internal static string eightball {
            get {
                return ResourceManager.GetString("eightball", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evil.
        /// </summary>
        internal static string evil {
            get {
                return ResourceManager.GetString("evil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kisses.
        /// </summary>
        internal static string kisses {
            get {
                return ResourceManager.GetString("kisses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mean.
        /// </summary>
        internal static string mean {
            get {
                return ResourceManager.GetString("mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sad.
        /// </summary>
        internal static string sad {
            get {
                return ResourceManager.GetString("sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shock.
        /// </summary>
        internal static string shock {
            get {
                return ResourceManager.GetString("shock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shy.
        /// </summary>
        internal static string shy {
            get {
                return ResourceManager.GetString("shy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sleepy.
        /// </summary>
        internal static string sleepy {
            get {
                return ResourceManager.GetString("sleepy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile.
        /// </summary>
        internal static string smile {
            get {
                return ResourceManager.GetString("smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tongue.
        /// </summary>
        internal static string tongue {
            get {
                return ResourceManager.GetString("tongue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wink.
        /// </summary>
        internal static string wink {
            get {
                return ResourceManager.GetString("wink", resourceCulture);
            }
        }
    }
}
