//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PMImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PMImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PMImages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmdelete.jpg.
        /// </summary>
        internal static string pmDeleteImg {
            get {
                return ResourceManager.GetString("pmDeleteImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmforward.jpg.
        /// </summary>
        internal static string pmForwardImg {
            get {
                return ResourceManager.GetString("pmForwardImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pminbox.jpg.
        /// </summary>
        internal static string pmInboxImg {
            get {
                return ResourceManager.GetString("pmInboxImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmmemberlist.jpg.
        /// </summary>
        internal static string pmMembersImg {
            get {
                return ResourceManager.GetString("pmMembersImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmnew.jpg.
        /// </summary>
        internal static string pmNewImg {
            get {
                return ResourceManager.GetString("pmNewImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmoutbox.jpg.
        /// </summary>
        internal static string pmOutboxImg {
            get {
                return ResourceManager.GetString("pmOutboxImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmprivpref.jpg.
        /// </summary>
        internal static string pmPreferencesImg {
            get {
                return ResourceManager.GetString("pmPreferencesImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/icon_pm_old.gif.
        /// </summary>
        internal static string pmRead {
            get {
                return ResourceManager.GetString("pmRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmreceive.jpg.
        /// </summary>
        internal static string pmReceiveImg {
            get {
                return ResourceManager.GetString("pmReceiveImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/pmreply.jpg.
        /// </summary>
        internal static string pmReplyImg {
            get {
                return ResourceManager.GetString("pmReplyImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to images/icon_pm_new.gif.
        /// </summary>
        internal static string pmUnread {
            get {
                return ResourceManager.GetString("pmUnread", resourceCulture);
            }
        }
    }
}
