<?xml version="1.0" encoding="utf-8"?><Database Name="ForumT" Class="MembershipDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="aspnet_Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="RoleId" AutoSync="OnInsert" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_MembersInRole" Member="MembersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="MembersInRole" />
      <Association Name="ForumRole_Role" Member="ForumRole" ThisKey="RoleId" OtherKey="RoleId" Type="ForumRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="aspnet_UsersInRoles" Member="MembersInRoles">
    <Type Name="MembersInRole">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Member_MembersInRole" Member="Member" ThisKey="UserId" OtherKey="UserId" Type="Member" IsForeignKey="true" />
      <Association Name="Role_MembersInRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="FORUM_MEMBERS" Member="Members">
    <Type Name="Member">
      <Column Name="MEMBER_ID" Member="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="M_STATUS" Member="Status" Storage="_IsLockedOut" Type="System.Int32" DbType="SmallInt" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="M_NAME" Member="Username" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="M_PASSWORD" Member="Password" Type="System.String" DbType="NVarChar(65) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="M_EMAIL" Member="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="M_COUNTRY" Member="Country" Storage="_M_COUNTRY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_LEVEL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_POSTS" Member="Posts" Storage="_M_POSTS" Type="System.Int32" DbType="Int" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="M_DATE" Member="CreatedDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_LASTHEREDATE" Member="LastLoginDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_LASTUPDATED" Member="LastActivityDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_TITLE" Member="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_LAST_IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_KEY" Member="PasswordAnswer" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_NEWEMAIL" Member="NewEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_PWKEY" Member="PasswordQuestion" Type="System.String" DbType="NVarChar(32)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="M_VALID" Member="IsApproved" Type="System.Boolean" DbType="SmallInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="M_LASTPOSTDATE" Member="LastPostDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="M_RECEIVE_EMAIL" Member="ReceiveEmails" Type="System.Int32" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="M_TIMEOFFSET" Member="TimeOffset" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Association Name="Member_MembersInRole" Member="MembersInRoles" ThisKey="UserId" OtherKey="UserId" Type="MembersInRole" />
      <Association Name="Member_MemberProfile" Member="MemberProfiles" ThisKey="UserId" OtherKey="UserId" Type="MemberProfile" Cardinality="One" />
      <Association Name="ForumModerator_Member" Member="ForumModerator" ThisKey="UserId" OtherKey="UserId" Type="ForumModerator" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="ProfileData" Member="MemberProfiles">
    <Type Name="MemberProfile">
      <Column Name="UserID" Member="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Skype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HideAge" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="LinkTarget" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FavLinks" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gravatar" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="BookMarks" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Member_MemberProfile" Member="Member" ThisKey="UserId" OtherKey="UserId" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="FORUM_ROLES" Member="ForumRoles">
    <Type Name="ForumRole">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Forum_id" Member="ForumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Role_Id" Member="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ForumRole_Role" Member="Roles" ThisKey="RoleId" OtherKey="RoleId" Type="Role" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="FORUM_MODERATOR" Member="ForumModerators">
    <Type Name="ForumModerator">
      <Column Name="MOD_ID" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FORUM_ID" Member="ForumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEMBER_ID" Member="UserId" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="MOD_TYPE" Member="ModeratorType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="ForumModerator_Member" Member="Members" ThisKey="UserId" OtherKey="UserId" Type="Member" Cardinality="One" />
    </Type>
  </Table>
  <Function Name="sys.sp_columns" Method="GetColumns">
    <Parameter Name="table_name" Type="System.String" DbType="NVarChar(384)" />
    <Parameter Name="table_owner" Type="System.String" DbType="NVarChar(384)" />
    <Parameter Name="table_qualifier" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="column_name" Type="System.String" DbType="NVarChar(384)" />
    <Parameter Name="ODBCVer" Parameter="oDBCVer" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_columnsResult">
      <Column Name="TABLE_QUALIFIER" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_OWNER" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TABLE_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="COLUMN_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="DATA_TYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TYPE_NAME" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PRECISION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SCALE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RADIX" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NULLABLE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="REMARKS" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="COLUMN_DEF" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="SQL_DATA_TYPE" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SQL_DATETIME_SUB" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="CHAR_OCTET_LENGTH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ORDINAL_POSITION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IS_NULLABLE" Type="System.String" DbType="VarChar(254)" CanBeNull="true" />
      <Column Name="SS_DATA_TYPE" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>