<?xml version="1.0" encoding="utf-8"?><Database Name="ForumT" Class="LookupsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="FORUM_MODERATOR" Member="ForumModerators">
    <Type Name="ForumModerator">
      <Column Name="MOD_ID" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FORUM_ID" Member="ForumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MEMBER_ID" Member="ModeratorId" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="MOD_TYPE" Member="ModType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="ForumModerator_Moderator" Member="Moderators" ThisKey="ModeratorId" OtherKey="ModeratorId" Type="Moderator" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="FORUM_MEMBERS" Member="Moderators">
    <Type Name="Moderator">
      <Column Name="MEMBER_ID" Member="ModeratorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="M_STATUS" Member="Status" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="M_NAME" Member="Name" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="M_USERNAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="M_PASSWORD" Type="System.String" DbType="NVarChar(65) NOT NULL" CanBeNull="false" />
      <Column Name="M_EMAIL" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="M_LEVEL" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="M_TITLE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ForumModerator_Moderator" Member="ForumModerator" ThisKey="ModeratorId" OtherKey="ModeratorId" Type="ForumModerator" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="FORUM_SUBSCRIPTIONS" Member="ForumSubscriptions">
    <Type Name="ForumSubscriptions">
      <Column Name="SUBSCRIPTION_ID" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MEMBER_ID" Member="MemberId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CAT_ID" Member="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TOPIC_ID" Member="TopicId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FORUM_ID" Member="ForumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>