<?xml version="1.0" encoding="utf-8"?><Database Name="Forum" Class="SnitzFaqDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="FORUM_FAQ_CAT" Member="FaqCategories">
    <Type Name="FaqCategory">
      <Column Name="FC_ID" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FC_DESCRIPTION" Member="Description" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FC_LANG_ID" Member="Language" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="FC_ORDER" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="FORUM_FAQ_INFO" Member="FaqInfos">
    <Type Name="FaqInfo">
      <Column Name="FI_ID" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FI_ORDER" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FI_LINK" Member="Anchor" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FI_LINK_TITLE" Member="Question" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FI_LINK_BODY" Member="Answer" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FI_CAT" Member="CatId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FI_LANG_ID" Member="Language" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
    </Type>
  </Table>
</Database>