//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class webResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal webResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.webResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Link.
        /// </summary>
        internal static string btnAddLink {
            get {
                return ResourceManager.GetString("btnAddLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Agree .
        /// </summary>
        internal static string btnAgree {
            get {
                return ResourceManager.GetString("btnAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete {
            get {
                return ResourceManager.GetString("btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string btnEdit {
            get {
                return ResourceManager.GetString("btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string btnNo {
            get {
                return ResourceManager.GetString("btnNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string btnOk {
            get {
                return ResourceManager.GetString("btnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string btnPrev {
            get {
                return ResourceManager.GetString("btnPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string btnPreview {
            get {
                return ResourceManager.GetString("btnPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Links.
        /// </summary>
        internal static string btnSaveLink {
            get {
                return ResourceManager.GetString("btnSaveLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Spelling.
        /// </summary>
        internal static string btnSpell {
            get {
                return ResourceManager.GetString("btnSpell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string btnUpload {
            get {
                return ResourceManager.GetString("btnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Avatar.
        /// </summary>
        internal static string btnUploadAvatar {
            get {
                return ResourceManager.GetString("btnUploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string btnYes {
            get {
                return ResourceManager.GetString("btnYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature checkbox checked by default?.
        /// </summary>
        internal static string cbxUseSigbyDefault {
            get {
                return ResourceManager.GetString("cbxUseSigbyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Signatures in Posts?.
        /// </summary>
        internal static string cbxViewSiginPost {
            get {
                return ResourceManager.GetString("cbxViewSiginPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created, but before you can login you must first verify your email address. A message has been sent to the email address you specified. Please check your email inbox and follow the instructions in that email to verify your account.
        /// </summary>
        internal static string EmailValMessage {
            get {
                return ResourceManager.GetString("EmailValMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Error.
        /// </summary>
        internal static string errError {
            get {
                return ResourceManager.GetString("errError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file type is not allowed..
        /// </summary>
        internal static string ErrFileTypeNotAllowed {
            get {
                return ResourceManager.GetString("ErrFileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flood control is enabled on this forum.&lt;br /&gt;&lt;br /&gt;Please try again later..
        /// </summary>
        internal static string errFloodError {
            get {
                return ResourceManager.GetString("errFloodError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You are not authorised to view this forum&lt;/p&gt;.
        /// </summary>
        internal static string errForumView {
            get {
                return ResourceManager.GetString("errForumView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML markup is not allowed..
        /// </summary>
        internal static string errHtml {
            get {
                return ResourceManager.GetString("errHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Forum ID was not valid&lt;/p&gt;.
        /// </summary>
        internal static string errInvalidForumId {
            get {
                return ResourceManager.GetString("errInvalidForumId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;QueryString was not Valid&lt;/p&gt;.
        /// </summary>
        internal static string errInvalidQueryString {
            get {
                return ResourceManager.GetString("errInvalidQueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Topic ID does not exist&lt;/p&gt;.
        /// </summary>
        internal static string errInvalidTopicId {
            get {
                return ResourceManager.GetString("errInvalidTopicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login attempt was not successful. Please try again..
        /// </summary>
        internal static string ErrLoginFailure {
            get {
                return ResourceManager.GetString("ErrLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be logged in to access this page, please enter your username and password.&lt;br /&gt;&lt;br /&gt;.
        /// </summary>
        internal static string ErrLoginRequired {
            get {
                return ResourceManager.GetString("ErrLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum number of files that you are allowed to upload..
        /// </summary>
        internal static string ErrMaxFilesExceeded {
            get {
                return ResourceManager.GetString("ErrMaxFilesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploading of this file will cause your space allocation to be exceeded..
        /// </summary>
        internal static string ErrMaxSpaceExceeded {
            get {
                return ResourceManager.GetString("ErrMaxSpaceExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not post an empty message.
        /// </summary>
        internal static string ErrNoMessage {
            get {
                return ResourceManager.GetString("ErrNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        internal static string ErrNoPassword {
            get {
                return ResourceManager.GetString("ErrNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;center&gt;&lt;br /&gt;No Records were found that matched your search criteria&lt;br /&gt;&lt;/center&gt;.
        /// </summary>
        internal static string ErrNoSearchResults {
            get {
                return ResourceManager.GetString("ErrNoSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply a value to search for.
        /// </summary>
        internal static string ErrNoSearchString {
            get {
                return ResourceManager.GetString("ErrNoSearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a subject for your post.
        /// </summary>
        internal static string ErrNoSubject {
            get {
                return ResourceManager.GetString("ErrNoSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorised to complete this action..
        /// </summary>
        internal static string ErrNotAuth {
            get {
                return ResourceManager.GetString("ErrNotAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Not Implemented.
        /// </summary>
        internal static string ErrNotImplemented {
            get {
                return ResourceManager.GetString("ErrNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Topics found.
        /// </summary>
        internal static string ErrNoTopics {
            get {
                return ResourceManager.GetString("ErrNoTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is Required.
        /// </summary>
        internal static string ErrNoUsername {
            get {
                return ResourceManager.GetString("ErrNoUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Only Administrators can edit other members profiles&lt;/p&gt;.
        /// </summary>
        internal static string errProfileEdit {
            get {
                return ResourceManager.GetString("errProfileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter some Keywords or a UserName, and Keywords must contain more than one character.
        /// </summary>
        internal static string ErrSearchFor {
            get {
                return ResourceManager.GetString("ErrSearchFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one Category or Forum.
        /// </summary>
        internal static string ErrSearchNoForum {
            get {
                return ResourceManager.GetString("ErrSearchNoForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You are not permitted to view that Topic&lt;/p&gt;.
        /// </summary>
        internal static string errTopicView {
            get {
                return ResourceManager.GetString("errTopicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large to upload.
        /// </summary>
        internal static string ErrUploadFileSize {
            get {
                return ResourceManager.GetString("ErrUploadFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not an Image.
        /// </summary>
        internal static string ErrUploadFileType {
            get {
                return ResourceManager.GetString("ErrUploadFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No File was uploaded.
        /// </summary>
        internal static string ErrUploadNoFile {
            get {
                return ResourceManager.GetString("ErrUploadNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Forum is locked, no posting allowed).
        /// </summary>
        internal static string ForumIsLocked {
            get {
                return ResourceManager.GetString("ForumIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string lblAbout {
            get {
                return ResourceManager.GetString("lblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string lblAge {
            get {
                return ResourceManager.GetString("lblAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM Screen Name.
        /// </summary>
        internal static string lblAIM {
            get {
                return ResourceManager.GetString("lblAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed File Types.
        /// </summary>
        internal static string lblAllowedFileTypes {
            get {
                return ResourceManager.GetString("lblAllowedFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic can be archived.
        /// </summary>
        internal static string lblArchive {
            get {
                return ResourceManager.GetString("lblArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar.
        /// </summary>
        internal static string lblAvatar {
            get {
                return ResourceManager.GetString("lblAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to Forum.
        /// </summary>
        internal static string lblBack {
            get {
                return ResourceManager.GetString("lblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        internal static string lblBiog {
            get {
                return ResourceManager.GetString("lblBiog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Weblog.
        /// </summary>
        internal static string lblBlogTitle {
            get {
                return ResourceManager.GetString("lblBlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Edit.
        /// </summary>
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category/Forum.
        /// </summary>
        internal static string lblCatForum {
            get {
                return ResourceManager.GetString("lblCatForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        internal static string lblChangeEmail {
            get {
                return ResourceManager.GetString("lblChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        internal static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters Remaining (300 MAX).
        /// </summary>
        internal static string lblCharactersRemaining {
            get {
                return ResourceManager.GetString("lblCharactersRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string lblCity {
            get {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment(s).
        /// </summary>
        internal static string lblComments {
            get {
                return ResourceManager.GetString("lblComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Info.
        /// </summary>
        internal static string lblContactInfo {
            get {
                return ResourceManager.GetString("lblContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact me via {0}.
        /// </summary>
        internal static string lblContactMe {
            get {
                return ResourceManager.GetString("lblContactMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string lblCountry {
            get {
                return ResourceManager.GetString("lblCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete your registration, please provide a username for your membership and a valid email address, a confirmation email will be sent to this address.&lt;br/&gt;&lt;b&gt;If you have spam filtering, please make sure that you allow emails from&lt;/b&gt;&amp;nbsp;.
        /// </summary>
        internal static string lblCUserStep1 {
            get {
                return ResourceManager.GetString("lblCUserStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string lblDate {
            get {
                return ResourceManager.GetString("lblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string lblDay {
            get {
                return ResourceManager.GetString("lblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        internal static string lblDelCategory {
            get {
                return ResourceManager.GetString("lblDelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Member.
        /// </summary>
        internal static string lblDeleteUser {
            get {
                return ResourceManager.GetString("lblDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Forum.
        /// </summary>
        internal static string lblDelForum {
            get {
                return ResourceManager.GetString("lblDelForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Post.
        /// </summary>
        internal static string lblDelPost {
            get {
                return ResourceManager.GetString("lblDelPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Reply.
        /// </summary>
        internal static string lblDelReply {
            get {
                return ResourceManager.GetString("lblDelReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Topic.
        /// </summary>
        internal static string lblDelTopic {
            get {
                return ResourceManager.GetString("lblDelTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string lblDOB {
            get {
                return ResourceManager.GetString("lblDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        internal static string lblEditCategory {
            get {
                return ResourceManager.GetString("lblEditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited on {0} by {1}.
        /// </summary>
        internal static string lblEditedBy {
            get {
                return ResourceManager.GetString("lblEditedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Forum properties.
        /// </summary>
        internal static string lblEditForum {
            get {
                return ResourceManager.GetString("lblEditForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        internal static string lblEditPost {
            get {
                return ResourceManager.GetString("lblEditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reply.
        /// </summary>
        internal static string lblEditReply {
            get {
                return ResourceManager.GetString("lblEditReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Topic.
        /// </summary>
        internal static string lblEditTopic {
            get {
                return ResourceManager.GetString("lblEditTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string lblEditUser {
            get {
                return ResourceManager.GetString("lblEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to send.
        /// </summary>
        internal static string lblEmailMessage {
            get {
                return ResourceManager.GetString("lblEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all posts in Forum.
        /// </summary>
        internal static string lblEmptyForum {
            get {
                return ResourceManager.GetString("lblEmptyForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lblEnglishLang {
            get {
                return ResourceManager.GetString("lblEnglishLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Info.
        /// </summary>
        internal static string lblExtraInfo {
            get {
                return ResourceManager.GetString("lblExtraInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Links.
        /// </summary>
        internal static string lblFavLinks {
            get {
                return ResourceManager.GetString("lblFavLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string lblFile {
            get {
                return ResourceManager.GetString("lblFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find posts from.
        /// </summary>
        internal static string lblFindFrom {
            get {
                return ResourceManager.GetString("lblFindFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        internal static string lblFor {
            get {
                return ResourceManager.GetString("lblFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string lblForum {
            get {
                return ResourceManager.GetString("lblForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForumInfo.
        /// </summary>
        internal static string lblForumInfo {
            get {
                return ResourceManager.GetString("lblForumInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum is Locked, No Posting Allowed..
        /// </summary>
        internal static string lblForumLocked {
            get {
                return ResourceManager.GetString("lblForumLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snitz Forum.
        /// </summary>
        internal static string lblForumTitle {
            get {
                return ResourceManager.GetString("lblForumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string lblFrenchLang {
            get {
                return ResourceManager.GetString("lblFrenchLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string lblFrom {
            get {
                return ResourceManager.GetString("lblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string lblFullName {
            get {
                return ResourceManager.GetString("lblFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string lblGermanLang {
            get {
                return ResourceManager.GetString("lblGermanLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to top of page.
        /// </summary>
        internal static string lblGotoTop {
            get {
                return ResourceManager.GetString("lblGotoTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests.
        /// </summary>
        internal static string lblGuests {
            get {
                return ResourceManager.GetString("lblGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Age from users.
        /// </summary>
        internal static string lblHideAge {
            get {
                return ResourceManager.GetString("lblHideAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide email address from users.
        /// </summary>
        internal static string lblHideEmail {
            get {
                return ResourceManager.GetString("lblHideEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interests.
        /// </summary>
        internal static string lblHobbies {
            get {
                return ResourceManager.GetString("lblHobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page Url.
        /// </summary>
        internal static string lblHomePage {
            get {
                return ResourceManager.GetString("lblHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostName.
        /// </summary>
        internal static string lblHost {
            get {
                return ResourceManager.GetString("lblHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Topic, contains {0} or more replies.
        /// </summary>
        internal static string lblHotTopics {
            get {
                return ResourceManager.GetString("lblHotTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        internal static string lblHyperlink {
            get {
                return ResourceManager.GetString("lblHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICQ Number.
        /// </summary>
        internal static string lblICQ {
            get {
                return ResourceManager.GetString("lblICQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include your profile signature..
        /// </summary>
        internal static string lblIncludeSig {
            get {
                return ResourceManager.GetString("lblIncludeSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address of poster.
        /// </summary>
        internal static string lblIP {
            get {
                return ResourceManager.GetString("lblIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        internal static string lblIrishLang {
            get {
                return ResourceManager.GetString("lblIrishLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string lblItalianLang {
            get {
                return ResourceManager.GetString("lblItalianLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string lblJapaneseLang {
            get {
                return ResourceManager.GetString("lblJapaneseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to.
        /// </summary>
        internal static string lblJumpTo {
            get {
                return ResourceManager.GetString("lblJumpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        internal static string lblLastPost {
            get {
                return ResourceManager.GetString("lblLastPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Last Post.
        /// </summary>
        internal static string lblLastPostJump {
            get {
                return ResourceManager.GetString("lblLastPostJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Last Edited.
        /// </summary>
        internal static string lblLastUpdated {
            get {
                return ResourceManager.GetString("lblLastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last activity .
        /// </summary>
        internal static string lblLastVisit {
            get {
                return ResourceManager.GetString("lblLastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        internal static string lblLatestNews {
            get {
                return ResourceManager.GetString("lblLatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Links.
        /// </summary>
        internal static string lblLinks {
            get {
                return ResourceManager.GetString("lblLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Topic.
        /// </summary>
        internal static string lblLock {
            get {
                return ResourceManager.GetString("lblLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Category.
        /// </summary>
        internal static string lblLockCat {
            get {
                return ResourceManager.GetString("lblLockCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum is Locked.
        /// </summary>
        internal static string lblLockedForum {
            get {
                return ResourceManager.GetString("lblLockedForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked topic.
        /// </summary>
        internal static string lblLockedTopic {
            get {
                return ResourceManager.GetString("lblLockedTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Forum.
        /// </summary>
        internal static string lblLockForum {
            get {
                return ResourceManager.GetString("lblLockForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock {0}&apos;s Account.
        /// </summary>
        internal static string lblLockUser {
            get {
                return ResourceManager.GetString("lblLockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Welcome back {0}.&lt;/b&gt; {1}  You last visited {2}.
        /// </summary>
        internal static string lblLoggedOn {
            get {
                return ResourceManager.GetString("lblLoggedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Login.
        /// </summary>
        internal static string lblLoginTitle {
            get {
                return ResourceManager.GetString("lblLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark all posts as read.
        /// </summary>
        internal static string lblMarkAllRead {
            get {
                return ResourceManager.GetString("lblMarkAllRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        internal static string lblMarStatus {
            get {
                return ResourceManager.GetString("lblMarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins have unlimited uploads.
        /// </summary>
        internal static string lblMaxAdminUploadSize {
            get {
                return ResourceManager.GetString("lblMaxAdminUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum File Size.
        /// </summary>
        internal static string lblMaxFileSize {
            get {
                return ResourceManager.GetString("lblMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allowed file uploads is &lt;b&gt;{0}&lt;/b&gt;..
        /// </summary>
        internal static string lblMaxUserUploadFiles {
            get {
                return ResourceManager.GetString("lblMaxUserUploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allowed total file size uploads is &lt;b&gt;{0}&lt;/b&gt;..
        /// </summary>
        internal static string lblMaxUserUploadSize {
            get {
                return ResourceManager.GetString("lblMaxUserUploadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        internal static string lblMemberID {
            get {
                return ResourceManager.GetString("lblMemberID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string lblMembers {
            get {
                return ResourceManager.GetString("lblMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined.
        /// </summary>
        internal static string lblMemberSince {
            get {
                return ResourceManager.GetString("lblMemberSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s AIM Options.
        /// </summary>
        internal static string lblMessengerAIM {
            get {
                return ResourceManager.GetString("lblMessengerAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Buddy List.
        /// </summary>
        internal static string lblMessengerBuddyList {
            get {
                return ResourceManager.GetString("lblMessengerBuddyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Chat window.
        /// </summary>
        internal static string lblMessengerChat {
            get {
                return ResourceManager.GetString("lblMessengerChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message to Member.
        /// </summary>
        internal static string lblMessengerSend {
            get {
                return ResourceManager.GetString("lblMessengerSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Skype Messenger address:.
        /// </summary>
        internal static string lblMessengerSkype {
            get {
                return ResourceManager.GetString("lblMessengerSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be a minimum of {0} years of age.
        /// </summary>
        internal static string lblMinAge {
            get {
                return ResourceManager.GetString("lblMinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Members: {0} &lt;br/&gt;Total Posts: {1} &lt;br/&gt;Last post {2} by: {3}.
        /// </summary>
        internal static string lblMiniStatsMembers {
            get {
                return ResourceManager.GetString("lblMiniStatsMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest member: {0}.
        /// </summary>
        internal static string lblMiniStatsNewMember {
            get {
                return ResourceManager.GetString("lblMiniStatsNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;a class=&apos;StatsLnks&apos; href=&apos;/Content/Forums/active.aspx&apos; title=&apos;View active topics&apos;&gt;active&lt;/a&gt; topic(s) since your last visit..
        /// </summary>
        internal static string lblMiniStatsTopics {
            get {
                return ResourceManager.GetString("lblMiniStatsTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Record.
        /// </summary>
        internal static string lblNew {
            get {
                return ResourceManager.GetString("lblNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Forum.
        /// </summary>
        internal static string lblNewForum {
            get {
                return ResourceManager.GetString("lblNewForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains New Posts.
        /// </summary>
        internal static string lblNewPosts {
            get {
                return ResourceManager.GetString("lblNewPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Topic.
        /// </summary>
        internal static string lblNewTopic {
            get {
                return ResourceManager.GetString("lblNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Url link.
        /// </summary>
        internal static string lblNewUrl {
            get {
                return ResourceManager.GetString("lblNewUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not archive topic.
        /// </summary>
        internal static string lblNoArchive {
            get {
                return ResourceManager.GetString("lblNoArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-english filenames might not work correctly.
        /// </summary>
        internal static string lblNonEnglishFileNames {
            get {
                return ResourceManager.GetString("lblNonEnglishFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Shared.
        /// </summary>
        internal static string lblNotShared {
            get {
                return ResourceManager.GetString("lblNotShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        internal static string lblOccupation {
            get {
                return ResourceManager.GetString("lblOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new Posts.
        /// </summary>
        internal static string lblOldPosts {
            get {
                return ResourceManager.GetString("lblOldPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string lblOptions {
            get {
                return ResourceManager.GetString("lblOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Info.
        /// </summary>
        internal static string lblOtherInfo {
            get {
                return ResourceManager.GetString("lblOtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string lblPage {
            get {
                return ResourceManager.GetString("lblPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1} pages.
        /// </summary>
        internal static string lblPagerButton {
            get {
                return ResourceManager.GetString("lblPagerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0} pages.
        /// </summary>
        internal static string lblPagerDropdown {
            get {
                return ResourceManager.GetString("lblPagerDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persian(Farsi).
        /// </summary>
        internal static string lblPersianLang {
            get {
                return ResourceManager.GetString("lblPersianLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string lblPostAuthor {
            get {
                return ResourceManager.GetString("lblPostAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted:.
        /// </summary>
        internal static string lblPostDate {
            get {
                return ResourceManager.GetString("lblPostDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check here to lock the topic after this post..
        /// </summary>
        internal static string lblPostLockTopic {
            get {
                return ResourceManager.GetString("lblPostLockTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check here to make this topic sticky..
        /// </summary>
        internal static string lblPostMakeSticky {
            get {
                return ResourceManager.GetString("lblPostMakeSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string lblPosts {
            get {
                return ResourceManager.GetString("lblPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Message.
        /// </summary>
        internal static string lblPreview {
            get {
                return ResourceManager.GetString("lblPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string lblPrintTopic {
            get {
                return ResourceManager.GetString("lblPrintTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lblProfile {
            get {
                return ResourceManager.GetString("lblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Profile.
        /// </summary>
        internal static string lblProfileTitle {
            get {
                return ResourceManager.GetString("lblProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Signature.
        /// </summary>
        internal static string lblQRSig {
            get {
                return ResourceManager.GetString("lblQRSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Reply.
        /// </summary>
        internal static string lblQuickReplyHeader {
            get {
                return ResourceManager.GetString("lblQuickReplyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Quote.
        /// </summary>
        internal static string lblQuote {
            get {
                return ResourceManager.GetString("lblQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Email.
        /// </summary>
        internal static string lblReceiveEmail {
            get {
                return ResourceManager.GetString("lblReceiveEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Topics.
        /// </summary>
        internal static string lblRecentTopics {
            get {
                return ResourceManager.GetString("lblRecentTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies.
        /// </summary>
        internal static string lblReplies {
            get {
                return ResourceManager.GetString("lblReplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string lblReply {
            get {
                return ResourceManager.GetString("lblReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply with Quote.
        /// </summary>
        internal static string lblReplyQuote {
            get {
                return ResourceManager.GetString("lblReplyQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to Topic.
        /// </summary>
        internal static string lblReplyToTopic {
            get {
                return ResourceManager.GetString("lblReplyToTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !! Awaiting Moderation.
        /// </summary>
        internal static string lblRequireModeration {
            get {
                return ResourceManager.GetString("lblRequireModeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string lblRoleTitle {
            get {
                return ResourceManager.GetString("lblRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search archived posts.
        /// </summary>
        internal static string lblSearchArchive {
            get {
                return ResourceManager.GetString("lblSearchArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Date.
        /// </summary>
        internal static string lblSearchDate {
            get {
                return ResourceManager.GetString("lblSearchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact name.
        /// </summary>
        internal static string lblSearchExactName {
            get {
                return ResourceManager.GetString("lblSearchExactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Forums.
        /// </summary>
        internal static string lblSearchForums {
            get {
                return ResourceManager.GetString("lblSearchForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in.
        /// </summary>
        internal static string lblSearchIn {
            get {
                return ResourceManager.GetString("lblSearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search term(s).
        /// </summary>
        internal static string lblSearchKeywords {
            get {
                return ResourceManager.GetString("lblSearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Username.
        /// </summary>
        internal static string lblSearchUser {
            get {
                return ResourceManager.GetString("lblSearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Topic.
        /// </summary>
        internal static string lblSendTopic {
            get {
                return ResourceManager.GetString("lblSendTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;You received this message from {2}&lt;/p&gt;.
        /// </summary>
        internal static string lblSendTopicFrom {
            get {
                return ResourceManager.GetString("lblSendTopicFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}.
        /// </summary>
        internal static string lblSendTopicHello {
            get {
                return ResourceManager.GetString("lblSendTopicHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;I thought you might be interested in the following post :&lt;br /&gt;&lt;br /&gt;&lt;a href=&apos;{0}&apos;&gt;{1}&lt;/a&gt;&lt;/p&gt;.
        /// </summary>
        internal static string lblSendTopicMessage {
            get {
                return ResourceManager.GetString("lblSendTopicMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent From {0}  by {1}.
        /// </summary>
        internal static string lblSendTopicSubject {
            get {
                return ResourceManager.GetString("lblSendTopicSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string lblShare {
            get {
                return ResourceManager.GetString("lblShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show results as.
        /// </summary>
        internal static string lblShowAs {
            get {
                return ResourceManager.GetString("lblShowAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show IP of Poster.
        /// </summary>
        internal static string lblShowIP {
            get {
                return ResourceManager.GetString("lblShowIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string lblSig {
            get {
                return ResourceManager.GetString("lblSig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Settings.
        /// </summary>
        internal static string lblSiteInfo {
            get {
                return ResourceManager.GetString("lblSiteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype Name.
        /// </summary>
        internal static string lblSkype {
            get {
                return ResourceManager.GetString("lblSkype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort results by.
        /// </summary>
        internal static string lblSortResults {
            get {
                return ResourceManager.GetString("lblSortResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        internal static string lblState {
            get {
                return ResourceManager.GetString("lblState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;Forum Statistics.
        /// </summary>
        internal static string lblStatistics {
            get {
                return ResourceManager.GetString("lblStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} archived posts in {1} archived topic(s).
        /// </summary>
        internal static string lblStatsArchive {
            get {
                return ResourceManager.GetString("lblStatsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You last visited .
        /// </summary>
        internal static string lblStatsLastVisit {
            get {
                return ResourceManager.GetString("lblStatsLastVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} &lt;a class=&apos;StatsLnks&apos; href=&apos;/Content/Forums/members.aspx&apos; title=&apos;View list of forum members&apos;&gt;Members&lt;/a&gt; have made {2} posts, with the last post {3} by: {4}.
        /// </summary>
        internal static string lblStatsMembers {
            get {
                return ResourceManager.GetString("lblStatsMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members online: {0}.
        /// </summary>
        internal static string lblStatsMembersOnline {
            get {
                return ResourceManager.GetString("lblStatsMembersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please welcome our newest member: {0}.
        /// </summary>
        internal static string lblStatsNewMember {
            get {
                return ResourceManager.GetString("lblStatsNewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently {0} topics and there are {1} &lt;a class=&apos;StatsLnks&apos; href=&apos;/Content/Forums/active.aspx&apos; title=&apos;View active topics&apos;&gt;active&lt;/a&gt; topic(s) since you last visited..
        /// </summary>
        internal static string lblStatsTopics {
            get {
                return ResourceManager.GetString("lblStatsTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Topic Sticky.
        /// </summary>
        internal static string lblStick {
            get {
                return ResourceManager.GetString("lblStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sticky Topic.
        /// </summary>
        internal static string lblStickyTopic {
            get {
                return ResourceManager.GetString("lblStickyTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to posts in this forum.
        /// </summary>
        internal static string lblSubscribeForum {
            get {
                return ResourceManager.GetString("lblSubscribeForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify me when someone replies to this topic.
        /// </summary>
        internal static string lblSubscribeTopic {
            get {
                return ResourceManager.GetString("lblSubscribeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure ?.
        /// </summary>
        internal static string lblSure {
            get {
                return ResourceManager.GetString("lblSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Theme.
        /// </summary>
        internal static string lblThemes {
            get {
                return ResourceManager.GetString("lblThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset from GMT.
        /// </summary>
        internal static string lblTimeOffset {
            get {
                return ResourceManager.GetString("lblTimeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page was generated in {0} seconds.
        /// </summary>
        internal static string lblTimer {
            get {
                return ResourceManager.GetString("lblTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        internal static string lblTimeZone {
            get {
                return ResourceManager.GetString("lblTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string lblTo {
            get {
                return ResourceManager.GetString("lblTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string lblTopic {
            get {
                return ResourceManager.GetString("lblTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic is Locked, No Replies Allowed..
        /// </summary>
        internal static string lblTopicLocked {
            get {
                return ResourceManager.GetString("lblTopicLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        internal static string lblTopics {
            get {
                return ResourceManager.GetString("lblTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Lock Record.
        /// </summary>
        internal static string lblUnlock {
            get {
                return ResourceManager.GetString("lblUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Lock Category.
        /// </summary>
        internal static string lblUnLockCat {
            get {
                return ResourceManager.GetString("lblUnLockCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Lock Forum.
        /// </summary>
        internal static string lblUnLockForum {
            get {
                return ResourceManager.GetString("lblUnLockForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Lock {0}&apos;s Account.
        /// </summary>
        internal static string lblUnlockUser {
            get {
                return ResourceManager.GetString("lblUnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un-Stick Topic.
        /// </summary>
        internal static string lblUnstick {
            get {
                return ResourceManager.GetString("lblUnstick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove subscription for this forum.
        /// </summary>
        internal static string lblUnSubscribeForum {
            get {
                return ResourceManager.GetString("lblUnSubscribeForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove notifications for this topic.
        /// </summary>
        internal static string lblUnSubscribeTopic {
            get {
                return ResourceManager.GetString("lblUnSubscribeTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file to server.
        /// </summary>
        internal static string lblUpload {
            get {
                return ResourceManager.GetString("lblUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully.
        /// </summary>
        internal static string lblUploadSuccess {
            get {
                return ResourceManager.GetString("lblUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string lblViewCount {
            get {
                return ResourceManager.GetString("lblViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View {0}&apos;s Profile.
        /// </summary>
        internal static string lblViewProfile {
            get {
                return ResourceManager.GetString("lblViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Members Home Page.
        /// </summary>
        internal static string lblVisitHomePage {
            get {
                return ResourceManager.GetString("lblVisitHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yahoo! Handle.
        /// </summary>
        internal static string lblYAHOO {
            get {
                return ResourceManager.GetString("lblYAHOO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;NOTE:&lt;/b&gt; You must have AOL Instant Messenger installed in order for these functions to work properly..
        /// </summary>
        internal static string litMessengerText {
            get {
                return ResourceManager.GetString("litMessengerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Home Page specified.
        /// </summary>
        internal static string NoHomePage {
            get {
                return ResourceManager.GetString("NoHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnHold.
        /// </summary>
        internal static string OnHold {
            get {
                return ResourceManager.GetString("OnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        internal static string TextDirection {
            get {
                return ResourceManager.GetString("TextDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        internal static string TextDirectionWord {
            get {
                return ResourceManager.GetString("TextDirectionWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic is on hold.
        /// </summary>
        internal static string TopicOnHold {
            get {
                return ResourceManager.GetString("TopicOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Topics since your last visit.
        /// </summary>
        internal static string ttlActivePage {
            get {
                return ResourceManager.GetString("ttlActivePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Home Page.
        /// </summary>
        internal static string ttlDefaultPage {
            get {
                return ResourceManager.GetString("ttlDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Forum : {1}.
        /// </summary>
        internal static string ttlForumPage {
            get {
                return ResourceManager.GetString("ttlForumPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Login Page.
        /// </summary>
        internal static string ttlLoginPage {
            get {
                return ResourceManager.GetString("ttlLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member List.
        /// </summary>
        internal static string ttlMembersPage {
            get {
                return ResourceManager.GetString("ttlMembersPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Policy.
        /// </summary>
        internal static string ttlPolicyPage {
            get {
                return ResourceManager.GetString("ttlPolicyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Record.
        /// </summary>
        internal static string ttlPopupDel {
            get {
                return ResourceManager.GetString("ttlPopupDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        internal static string ttlPopupEmail {
            get {
                return ResourceManager.GetString("ttlPopupEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger Window.
        /// </summary>
        internal static string ttlPopupMessenger {
            get {
                return ResourceManager.GetString("ttlPopupMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Topic.
        /// </summary>
        internal static string ttlPopupSendTopic {
            get {
                return ResourceManager.GetString("ttlPopupSendTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        internal static string ttlPopupUpload {
            get {
                return ResourceManager.GetString("ttlPopupUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View members IP.
        /// </summary>
        internal static string ttlPopupViewIP {
            get {
                return ResourceManager.GetString("ttlPopupViewIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Form.
        /// </summary>
        internal static string ttlPostMessage {
            get {
                return ResourceManager.GetString("ttlPostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Profile.
        /// </summary>
        internal static string ttlProfilePage {
            get {
                return ResourceManager.GetString("ttlProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Forums.
        /// </summary>
        internal static string ttlSearchPage {
            get {
                return ResourceManager.GetString("ttlSearchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : {1}.
        /// </summary>
        internal static string ttlTopicPage {
            get {
                return ResourceManager.GetString("ttlTopicPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmoderated post.
        /// </summary>
        internal static string Unmoderatedpost {
            get {
                return ResourceManager.GetString("Unmoderatedpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic contains unmoderated posts.
        /// </summary>
        internal static string UnmoderatedPosts {
            get {
                return ResourceManager.GetString("UnmoderatedPosts", resourceCulture);
            }
        }
    }
}
